name: Deploy FastAPI

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Deploy FastAPI to server
        env:  # 필요한 환경 변수 설정
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST << 'EOF'
            echo "SSH Connection Successful!"
            cd /home/ubuntu/22-5-team5-server
            git config pull.rebase false
            git pull origin main
            poetry install --no-root
            poetry run pgrep -f "uvicorn" && pkill -f "uvicorn" || true
            nohup env ENV=prod poetry run uvicorn wastory.main:app --host 0.0.0.0 --port 8000 > fastapi.log 2>&1 &
            disown

            echo "Deployment completed. Here are the logs:"
            tail -n 20 fastapi.log
          EOF
