name: PR CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests and Lint
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout 코드
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Python 설정 (3.11 고정)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 3. Dependencies 설치
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      # 4. Lint 검사
      - name: Run flake8
        run: poetry run flake8 .

      # 5. 유닛 테스트 실행
      - name: Run pytest
        run: poetry run pytest --cov=.
